import js from '@eslint/js'
import prettierConfig from 'eslint-config-prettier'

export default [
    js.configs.recommended,
    prettierConfig,
    {
        files: ['src/**/*.js', 'server.js'],
        languageOptions: {
            ecmaVersion: 2024,
            sourceType: 'module',
            globals: {
                AbortController: 'readonly',
                AbortSignal: 'readonly',
                Blob: 'readonly',
                Buffer: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                HTMLElement: 'readonly',
                IntersectionObserver: 'readonly',
                TextDecoder: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                clearInterval: 'readonly',
                clearTimeout: 'readonly',
                console: 'readonly',
                crypto: 'readonly',
                customElements: 'readonly',
                document: 'readonly',
                fetch: 'readonly',
                getComputedStyle: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                process: 'readonly',
                requestAnimationFrame: 'readonly',
                sessionStorage: 'readonly',
                setInterval: 'readonly',
                setTimeout: 'readonly',
                window: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-console': 'off',
            'prefer-const': 'error',
            'no-var': 'error',
            eqeqeq: ['error', 'always'],
            'no-duplicate-imports': 'error',
        },
    },
    {
        files: ['tests/**/*.js'],
        languageOptions: {
            ecmaVersion: 2024,
            sourceType: 'module',
            globals: {
                console: 'readonly',
                navigator: 'readonly',
                process: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'prefer-const': 'error',
            'no-var': 'error',
            eqeqeq: ['error', 'always'],
            'no-duplicate-imports': 'error',
        },
    },
    {
        ignores: ['dist/**', 'node_modules/**', 'playwright-report/**', 'test-results/**', 'playwright.config.js'],
    },
]
